//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cena_wynajmu
    {
        public int id_cena_wynajmu { get; set; }
        public decimal cena_wynajmu1 { get; set; }
        public System.DateTime poczatek_obowiazywania_ceny { get; set; }
        public System.DateTime koniec_obowiazywania_ceny { get; set; }
        public int samochody_id_samochodu { get; set; }
    
        public virtual samochody samochody { get; set; }
    }
}
