//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WypozyczalniaEntities : DbContext
    {
        public WypozyczalniaEntities()
            : base("name=WypozyczalniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adres_klienta> adres_klienta { get; set; }
        public virtual DbSet<cena_wynajmu> cena_wynajmu { get; set; }
        public virtual DbSet<dane_samochodu> dane_samochodu { get; set; }
        public virtual DbSet<klient> klient { get; set; }
        public virtual DbSet<pracownik> pracownik { get; set; }
        public virtual DbSet<samochody> samochody { get; set; }
        public virtual DbSet<uzytkownicy> uzytkownicy { get; set; }
        public virtual DbSet<wypozyczenia> wypozyczenia { get; set; }
    }
}
