//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wypozyczenia
    {
        public int id_wypozyczenia { get; set; }
        public int id_klienta { get; set; }
        public int id_pracownika { get; set; }
        public int id_samochodu { get; set; }
        public System.DateTime data_wypozyczenia { get; set; }
        public System.DateTime data_oddania { get; set; }
        public byte stan_wypozyczenia { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual pracownik pracownik { get; set; }
        public virtual samochody samochody { get; set; }
    }
}
