#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Wypozyczalnia")]
	public partial class projektDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadres_klienta(adres_klienta instance);
    partial void Updateadres_klienta(adres_klienta instance);
    partial void Deleteadres_klienta(adres_klienta instance);
    partial void Insertcena_wynajmu(cena_wynajmu instance);
    partial void Updatecena_wynajmu(cena_wynajmu instance);
    partial void Deletecena_wynajmu(cena_wynajmu instance);
    partial void Insertdane_samochodu(dane_samochodu instance);
    partial void Updatedane_samochodu(dane_samochodu instance);
    partial void Deletedane_samochodu(dane_samochodu instance);
    partial void Insertklient(klient instance);
    partial void Updateklient(klient instance);
    partial void Deleteklient(klient instance);
    partial void Insertpracownik(pracownik instance);
    partial void Updatepracownik(pracownik instance);
    partial void Deletepracownik(pracownik instance);
    partial void Insertsamochodyt(samochodyt instance);
    partial void Updatesamochodyt(samochodyt instance);
    partial void Deletesamochodyt(samochodyt instance);
    partial void Insertuzytkownicy(uzytkownicy instance);
    partial void Updateuzytkownicy(uzytkownicy instance);
    partial void Deleteuzytkownicy(uzytkownicy instance);
    partial void Insertwypozyczenia(wypozyczenia instance);
    partial void Updatewypozyczenia(wypozyczenia instance);
    partial void Deletewypozyczenia(wypozyczenia instance);
    #endregion
		
		public projektDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WypozyczalniaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public projektDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public projektDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public projektDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public projektDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<adres_klienta> adres_klientas
		{
			get
			{
				return this.GetTable<adres_klienta>();
			}
		}
		
		public System.Data.Linq.Table<cena_wynajmu> cena_wynajmus
		{
			get
			{
				return this.GetTable<cena_wynajmu>();
			}
		}
		
		public System.Data.Linq.Table<dane_samochodu> dane_samochodus
		{
			get
			{
				return this.GetTable<dane_samochodu>();
			}
		}
		
		public System.Data.Linq.Table<klient> klients
		{
			get
			{
				return this.GetTable<klient>();
			}
		}
		
		public System.Data.Linq.Table<pracownik> pracowniks
		{
			get
			{
				return this.GetTable<pracownik>();
			}
		}
		
		public System.Data.Linq.Table<samochodyt> samochodyts
		{
			get
			{
				return this.GetTable<samochodyt>();
			}
		}
		
		public System.Data.Linq.Table<uzytkownicy> uzytkownicies
		{
			get
			{
				return this.GetTable<uzytkownicy>();
			}
		}
		
		public System.Data.Linq.Table<wypozyczenia> wypozyczenias
		{
			get
			{
				return this.GetTable<wypozyczenia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.adres_klienta")]
	public partial class adres_klienta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_adres_klienta;
		
		private string _kod_miasta;
		
		private string _miasto;
		
		private string _ulica;
		
		private string _nr_domu;
		
		private string _nr_mieszkania;
		
		private EntitySet<klient> _klients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_adres_klientaChanging(int value);
    partial void Onid_adres_klientaChanged();
    partial void Onkod_miastaChanging(string value);
    partial void Onkod_miastaChanged();
    partial void OnmiastoChanging(string value);
    partial void OnmiastoChanged();
    partial void OnulicaChanging(string value);
    partial void OnulicaChanged();
    partial void Onnr_domuChanging(string value);
    partial void Onnr_domuChanged();
    partial void Onnr_mieszkaniaChanging(string value);
    partial void Onnr_mieszkaniaChanged();
    #endregion
		
		public adres_klienta()
		{
			this._klients = new EntitySet<klient>(new Action<klient>(this.attach_klients), new Action<klient>(this.detach_klients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_adres_klienta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_adres_klienta
		{
			get
			{
				return this._id_adres_klienta;
			}
			set
			{
				if ((this._id_adres_klienta != value))
				{
					this.Onid_adres_klientaChanging(value);
					this.SendPropertyChanging();
					this._id_adres_klienta = value;
					this.SendPropertyChanged("id_adres_klienta");
					this.Onid_adres_klientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod_miasta", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string kod_miasta
		{
			get
			{
				return this._kod_miasta;
			}
			set
			{
				if ((this._kod_miasta != value))
				{
					this.Onkod_miastaChanging(value);
					this.SendPropertyChanging();
					this._kod_miasta = value;
					this.SendPropertyChanged("kod_miasta");
					this.Onkod_miastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miasto", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string miasto
		{
			get
			{
				return this._miasto;
			}
			set
			{
				if ((this._miasto != value))
				{
					this.OnmiastoChanging(value);
					this.SendPropertyChanging();
					this._miasto = value;
					this.SendPropertyChanged("miasto");
					this.OnmiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ulica", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string ulica
		{
			get
			{
				return this._ulica;
			}
			set
			{
				if ((this._ulica != value))
				{
					this.OnulicaChanging(value);
					this.SendPropertyChanging();
					this._ulica = value;
					this.SendPropertyChanged("ulica");
					this.OnulicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_domu", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string nr_domu
		{
			get
			{
				return this._nr_domu;
			}
			set
			{
				if ((this._nr_domu != value))
				{
					this.Onnr_domuChanging(value);
					this.SendPropertyChanging();
					this._nr_domu = value;
					this.SendPropertyChanged("nr_domu");
					this.Onnr_domuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_mieszkania", DbType="VarChar(5)")]
		public string nr_mieszkania
		{
			get
			{
				return this._nr_mieszkania;
			}
			set
			{
				if ((this._nr_mieszkania != value))
				{
					this.Onnr_mieszkaniaChanging(value);
					this.SendPropertyChanging();
					this._nr_mieszkania = value;
					this.SendPropertyChanged("nr_mieszkania");
					this.Onnr_mieszkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="adres_klienta_klient", Storage="_klients", ThisKey="id_adres_klienta", OtherKey="id_adres_klienta")]
		public EntitySet<klient> klients
		{
			get
			{
				return this._klients;
			}
			set
			{
				this._klients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_klients(klient entity)
		{
			this.SendPropertyChanging();
			entity.adres_klienta = this;
		}
		
		private void detach_klients(klient entity)
		{
			this.SendPropertyChanging();
			entity.adres_klienta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cena_wynajmu")]
	public partial class cena_wynajmu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cena_wynajmu;
		
		private decimal _cena_wynajmu1;
		
		private System.DateTime _poczatek_obowiazywania_ceny;
		
		private System.DateTime _koniec_obowiazywania_ceny;
		
		private int _samochody_id_samochodu;
		
		private EntityRef<samochodyt> _samochody;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cena_wynajmuChanging(int value);
    partial void Onid_cena_wynajmuChanged();
    partial void Oncena_wynajmu1Changing(decimal value);
    partial void Oncena_wynajmu1Changed();
    partial void Onpoczatek_obowiazywania_cenyChanging(System.DateTime value);
    partial void Onpoczatek_obowiazywania_cenyChanged();
    partial void Onkoniec_obowiazywania_cenyChanging(System.DateTime value);
    partial void Onkoniec_obowiazywania_cenyChanged();
    partial void Onsamochody_id_samochoduChanging(int value);
    partial void Onsamochody_id_samochoduChanged();
    #endregion
		
		public cena_wynajmu()
		{
			this._samochody = default(EntityRef<samochodyt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cena_wynajmu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cena_wynajmu
		{
			get
			{
				return this._id_cena_wynajmu;
			}
			set
			{
				if ((this._id_cena_wynajmu != value))
				{
					this.Onid_cena_wynajmuChanging(value);
					this.SendPropertyChanging();
					this._id_cena_wynajmu = value;
					this.SendPropertyChanged("id_cena_wynajmu");
					this.Onid_cena_wynajmuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cena_wynajmu", Storage="_cena_wynajmu1", DbType="Decimal(10,2) NOT NULL")]
		public decimal cena_wynajmu1
		{
			get
			{
				return this._cena_wynajmu1;
			}
			set
			{
				if ((this._cena_wynajmu1 != value))
				{
					this.Oncena_wynajmu1Changing(value);
					this.SendPropertyChanging();
					this._cena_wynajmu1 = value;
					this.SendPropertyChanged("cena_wynajmu1");
					this.Oncena_wynajmu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poczatek_obowiazywania_ceny", DbType="DateTime NOT NULL")]
		public System.DateTime poczatek_obowiazywania_ceny
		{
			get
			{
				return this._poczatek_obowiazywania_ceny;
			}
			set
			{
				if ((this._poczatek_obowiazywania_ceny != value))
				{
					this.Onpoczatek_obowiazywania_cenyChanging(value);
					this.SendPropertyChanging();
					this._poczatek_obowiazywania_ceny = value;
					this.SendPropertyChanged("poczatek_obowiazywania_ceny");
					this.Onpoczatek_obowiazywania_cenyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_koniec_obowiazywania_ceny", DbType="DateTime NOT NULL")]
		public System.DateTime koniec_obowiazywania_ceny
		{
			get
			{
				return this._koniec_obowiazywania_ceny;
			}
			set
			{
				if ((this._koniec_obowiazywania_ceny != value))
				{
					this.Onkoniec_obowiazywania_cenyChanging(value);
					this.SendPropertyChanging();
					this._koniec_obowiazywania_ceny = value;
					this.SendPropertyChanged("koniec_obowiazywania_ceny");
					this.Onkoniec_obowiazywania_cenyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_samochody_id_samochodu", DbType="Int NOT NULL")]
		public int samochody_id_samochodu
		{
			get
			{
				return this._samochody_id_samochodu;
			}
			set
			{
				if ((this._samochody_id_samochodu != value))
				{
					if (this._samochody.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsamochody_id_samochoduChanging(value);
					this.SendPropertyChanging();
					this._samochody_id_samochodu = value;
					this.SendPropertyChanged("samochody_id_samochodu");
					this.Onsamochody_id_samochoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="samochodyt_cena_wynajmu", Storage="_samochody", ThisKey="samochody_id_samochodu", OtherKey="id_samochodu", IsForeignKey=true)]
		public samochodyt samochodyt
		{
			get
			{
				return this._samochody.Entity;
			}
			set
			{
				samochodyt previousValue = this._samochody.Entity;
				if (((previousValue != value) 
							|| (this._samochody.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._samochody.Entity = null;
						previousValue.cena_wynajmus.Remove(this);
					}
					this._samochody.Entity = value;
					if ((value != null))
					{
						value.cena_wynajmus.Add(this);
						this._samochody_id_samochodu = value.id_samochodu;
					}
					else
					{
						this._samochody_id_samochodu = default(int);
					}
					this.SendPropertyChanged("samochodyt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dane_samochodu")]
	public partial class dane_samochodu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_danych_samochodu;
		
		private string _marka;
		
		private string _typ;
		
		private System.DateTime _rok_produkcji;
		
		private string _kolor;
		
		private string _poj_silnika;
		
		private string _przebieg;
		
		private string _dane_samochodu1;
		
		private int _id_samochodu;
		
		private EntityRef<samochodyt> _samochody;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_danych_samochoduChanging(int value);
    partial void Onid_danych_samochoduChanged();
    partial void OnmarkaChanging(string value);
    partial void OnmarkaChanged();
    partial void OntypChanging(string value);
    partial void OntypChanged();
    partial void Onrok_produkcjiChanging(System.DateTime value);
    partial void Onrok_produkcjiChanged();
    partial void OnkolorChanging(string value);
    partial void OnkolorChanged();
    partial void Onpoj_silnikaChanging(string value);
    partial void Onpoj_silnikaChanged();
    partial void OnprzebiegChanging(string value);
    partial void OnprzebiegChanged();
    partial void Ondane_samochodu1Changing(string value);
    partial void Ondane_samochodu1Changed();
    partial void Onid_samochoduChanging(int value);
    partial void Onid_samochoduChanged();
    #endregion
		
		public dane_samochodu()
		{
			this._samochody = default(EntityRef<samochodyt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_danych_samochodu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_danych_samochodu
		{
			get
			{
				return this._id_danych_samochodu;
			}
			set
			{
				if ((this._id_danych_samochodu != value))
				{
					this.Onid_danych_samochoduChanging(value);
					this.SendPropertyChanging();
					this._id_danych_samochodu = value;
					this.SendPropertyChanged("id_danych_samochodu");
					this.Onid_danych_samochoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marka", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string marka
		{
			get
			{
				return this._marka;
			}
			set
			{
				if ((this._marka != value))
				{
					this.OnmarkaChanging(value);
					this.SendPropertyChanging();
					this._marka = value;
					this.SendPropertyChanged("marka");
					this.OnmarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this.OntypChanging(value);
					this.SendPropertyChanging();
					this._typ = value;
					this.SendPropertyChanged("typ");
					this.OntypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rok_produkcji", DbType="DateTime NOT NULL")]
		public System.DateTime rok_produkcji
		{
			get
			{
				return this._rok_produkcji;
			}
			set
			{
				if ((this._rok_produkcji != value))
				{
					this.Onrok_produkcjiChanging(value);
					this.SendPropertyChanging();
					this._rok_produkcji = value;
					this.SendPropertyChanged("rok_produkcji");
					this.Onrok_produkcjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kolor", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string kolor
		{
			get
			{
				return this._kolor;
			}
			set
			{
				if ((this._kolor != value))
				{
					this.OnkolorChanging(value);
					this.SendPropertyChanging();
					this._kolor = value;
					this.SendPropertyChanged("kolor");
					this.OnkolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poj_silnika", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string poj_silnika
		{
			get
			{
				return this._poj_silnika;
			}
			set
			{
				if ((this._poj_silnika != value))
				{
					this.Onpoj_silnikaChanging(value);
					this.SendPropertyChanging();
					this._poj_silnika = value;
					this.SendPropertyChanged("poj_silnika");
					this.Onpoj_silnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_przebieg", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string przebieg
		{
			get
			{
				return this._przebieg;
			}
			set
			{
				if ((this._przebieg != value))
				{
					this.OnprzebiegChanging(value);
					this.SendPropertyChanging();
					this._przebieg = value;
					this.SendPropertyChanged("przebieg");
					this.OnprzebiegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dane_samochodu", Storage="_dane_samochodu1", DbType="VarChar(5)")]
		public string dane_samochodu1
		{
			get
			{
				return this._dane_samochodu1;
			}
			set
			{
				if ((this._dane_samochodu1 != value))
				{
					this.Ondane_samochodu1Changing(value);
					this.SendPropertyChanging();
					this._dane_samochodu1 = value;
					this.SendPropertyChanged("dane_samochodu1");
					this.Ondane_samochodu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_samochodu", DbType="Int NOT NULL")]
		public int id_samochodu
		{
			get
			{
				return this._id_samochodu;
			}
			set
			{
				if ((this._id_samochodu != value))
				{
					if (this._samochody.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_samochoduChanging(value);
					this.SendPropertyChanging();
					this._id_samochodu = value;
					this.SendPropertyChanged("id_samochodu");
					this.Onid_samochoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="samochodyt_dane_samochodu", Storage="_samochody", ThisKey="id_samochodu", OtherKey="id_samochodu", IsForeignKey=true)]
		public samochodyt samochodyt
		{
			get
			{
				return this._samochody.Entity;
			}
			set
			{
				samochodyt previousValue = this._samochody.Entity;
				if (((previousValue != value) 
							|| (this._samochody.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._samochody.Entity = null;
						previousValue.dane_samochodus.Remove(this);
					}
					this._samochody.Entity = value;
					if ((value != null))
					{
						value.dane_samochodus.Add(this);
						this._id_samochodu = value.id_samochodu;
					}
					else
					{
						this._id_samochodu = default(int);
					}
					this.SendPropertyChanged("samochodyt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.klient")]
	public partial class klient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_klienta;
		
		private string _imie;
		
		private string _nazwisko;
		
		private string _telefon;
		
		private int _id_adres_klienta;
		
		private int _uzytkownicy_id_uzytkownika;
		
		private EntitySet<wypozyczenia> _wypozyczenias;
		
		private EntityRef<adres_klienta> _adres_klienta;
		
		private EntityRef<uzytkownicy> _uzytkownicy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klientaChanging(int value);
    partial void Onid_klientaChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void Onid_adres_klientaChanging(int value);
    partial void Onid_adres_klientaChanged();
    partial void Onuzytkownicy_id_uzytkownikaChanging(int value);
    partial void Onuzytkownicy_id_uzytkownikaChanged();
    #endregion
		
		public klient()
		{
			this._wypozyczenias = new EntitySet<wypozyczenia>(new Action<wypozyczenia>(this.attach_wypozyczenias), new Action<wypozyczenia>(this.detach_wypozyczenias));
			this._adres_klienta = default(EntityRef<adres_klienta>);
			this._uzytkownicy = default(EntityRef<uzytkownicy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					this.Onid_klientaChanging(value);
					this.SendPropertyChanging();
					this._id_klienta = value;
					this.SendPropertyChanged("id_klienta");
					this.Onid_klientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_adres_klienta", DbType="Int NOT NULL")]
		public int id_adres_klienta
		{
			get
			{
				return this._id_adres_klienta;
			}
			set
			{
				if ((this._id_adres_klienta != value))
				{
					if (this._adres_klienta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_adres_klientaChanging(value);
					this.SendPropertyChanging();
					this._id_adres_klienta = value;
					this.SendPropertyChanged("id_adres_klienta");
					this.Onid_adres_klientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uzytkownicy_id_uzytkownika", DbType="Int NOT NULL")]
		public int uzytkownicy_id_uzytkownika
		{
			get
			{
				return this._uzytkownicy_id_uzytkownika;
			}
			set
			{
				if ((this._uzytkownicy_id_uzytkownika != value))
				{
					if (this._uzytkownicy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuzytkownicy_id_uzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._uzytkownicy_id_uzytkownika = value;
					this.SendPropertyChanged("uzytkownicy_id_uzytkownika");
					this.Onuzytkownicy_id_uzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="klient_wypozyczenia", Storage="_wypozyczenias", ThisKey="id_klienta", OtherKey="id_klienta")]
		public EntitySet<wypozyczenia> wypozyczenias
		{
			get
			{
				return this._wypozyczenias;
			}
			set
			{
				this._wypozyczenias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="adres_klienta_klient", Storage="_adres_klienta", ThisKey="id_adres_klienta", OtherKey="id_adres_klienta", IsForeignKey=true)]
		public adres_klienta adres_klienta
		{
			get
			{
				return this._adres_klienta.Entity;
			}
			set
			{
				adres_klienta previousValue = this._adres_klienta.Entity;
				if (((previousValue != value) 
							|| (this._adres_klienta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._adres_klienta.Entity = null;
						previousValue.klients.Remove(this);
					}
					this._adres_klienta.Entity = value;
					if ((value != null))
					{
						value.klients.Add(this);
						this._id_adres_klienta = value.id_adres_klienta;
					}
					else
					{
						this._id_adres_klienta = default(int);
					}
					this.SendPropertyChanged("adres_klienta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uzytkownicy_klient", Storage="_uzytkownicy", ThisKey="uzytkownicy_id_uzytkownika", OtherKey="id_uzytkownika", IsForeignKey=true)]
		public uzytkownicy uzytkownicy
		{
			get
			{
				return this._uzytkownicy.Entity;
			}
			set
			{
				uzytkownicy previousValue = this._uzytkownicy.Entity;
				if (((previousValue != value) 
							|| (this._uzytkownicy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._uzytkownicy.Entity = null;
						previousValue.klients.Remove(this);
					}
					this._uzytkownicy.Entity = value;
					if ((value != null))
					{
						value.klients.Add(this);
						this._uzytkownicy_id_uzytkownika = value.id_uzytkownika;
					}
					else
					{
						this._uzytkownicy_id_uzytkownika = default(int);
					}
					this.SendPropertyChanged("uzytkownicy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_wypozyczenias(wypozyczenia entity)
		{
			this.SendPropertyChanging();
			entity.klient = this;
		}
		
		private void detach_wypozyczenias(wypozyczenia entity)
		{
			this.SendPropertyChanging();
			entity.klient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pracownik")]
	public partial class pracownik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pracownika;
		
		private string _imie;
		
		private string _nazwisko;
		
		private string _kod_miasta;
		
		private string _miasto;
		
		private string _ulica;
		
		private int _uzytkownicy_id_uzytkownika;
		
		private EntitySet<wypozyczenia> _wypozyczenias;
		
		private EntityRef<uzytkownicy> _uzytkownicy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pracownikaChanging(int value);
    partial void Onid_pracownikaChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void Onkod_miastaChanging(string value);
    partial void Onkod_miastaChanged();
    partial void OnmiastoChanging(string value);
    partial void OnmiastoChanged();
    partial void OnulicaChanging(string value);
    partial void OnulicaChanged();
    partial void Onuzytkownicy_id_uzytkownikaChanging(int value);
    partial void Onuzytkownicy_id_uzytkownikaChanged();
    #endregion
		
		public pracownik()
		{
			this._wypozyczenias = new EntitySet<wypozyczenia>(new Action<wypozyczenia>(this.attach_wypozyczenias), new Action<wypozyczenia>(this.detach_wypozyczenias));
			this._uzytkownicy = default(EntityRef<uzytkownicy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pracownika", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pracownika
		{
			get
			{
				return this._id_pracownika;
			}
			set
			{
				if ((this._id_pracownika != value))
				{
					this.Onid_pracownikaChanging(value);
					this.SendPropertyChanging();
					this._id_pracownika = value;
					this.SendPropertyChanged("id_pracownika");
					this.Onid_pracownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod_miasta", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string kod_miasta
		{
			get
			{
				return this._kod_miasta;
			}
			set
			{
				if ((this._kod_miasta != value))
				{
					this.Onkod_miastaChanging(value);
					this.SendPropertyChanging();
					this._kod_miasta = value;
					this.SendPropertyChanged("kod_miasta");
					this.Onkod_miastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miasto", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string miasto
		{
			get
			{
				return this._miasto;
			}
			set
			{
				if ((this._miasto != value))
				{
					this.OnmiastoChanging(value);
					this.SendPropertyChanging();
					this._miasto = value;
					this.SendPropertyChanged("miasto");
					this.OnmiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ulica", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string ulica
		{
			get
			{
				return this._ulica;
			}
			set
			{
				if ((this._ulica != value))
				{
					this.OnulicaChanging(value);
					this.SendPropertyChanging();
					this._ulica = value;
					this.SendPropertyChanged("ulica");
					this.OnulicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uzytkownicy_id_uzytkownika", DbType="Int NOT NULL")]
		public int uzytkownicy_id_uzytkownika
		{
			get
			{
				return this._uzytkownicy_id_uzytkownika;
			}
			set
			{
				if ((this._uzytkownicy_id_uzytkownika != value))
				{
					if (this._uzytkownicy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuzytkownicy_id_uzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._uzytkownicy_id_uzytkownika = value;
					this.SendPropertyChanged("uzytkownicy_id_uzytkownika");
					this.Onuzytkownicy_id_uzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pracownik_wypozyczenia", Storage="_wypozyczenias", ThisKey="id_pracownika", OtherKey="id_pracownika")]
		public EntitySet<wypozyczenia> wypozyczenias
		{
			get
			{
				return this._wypozyczenias;
			}
			set
			{
				this._wypozyczenias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uzytkownicy_pracownik", Storage="_uzytkownicy", ThisKey="uzytkownicy_id_uzytkownika", OtherKey="id_uzytkownika", IsForeignKey=true)]
		public uzytkownicy uzytkownicy
		{
			get
			{
				return this._uzytkownicy.Entity;
			}
			set
			{
				uzytkownicy previousValue = this._uzytkownicy.Entity;
				if (((previousValue != value) 
							|| (this._uzytkownicy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._uzytkownicy.Entity = null;
						previousValue.pracowniks.Remove(this);
					}
					this._uzytkownicy.Entity = value;
					if ((value != null))
					{
						value.pracowniks.Add(this);
						this._uzytkownicy_id_uzytkownika = value.id_uzytkownika;
					}
					else
					{
						this._uzytkownicy_id_uzytkownika = default(int);
					}
					this.SendPropertyChanged("uzytkownicy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_wypozyczenias(wypozyczenia entity)
		{
			this.SendPropertyChanging();
			entity.pracownik = this;
		}
		
		private void detach_wypozyczenias(wypozyczenia entity)
		{
			this.SendPropertyChanging();
			entity.pracownik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.samochody")]
	public partial class samochodyt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_samochodu;
		
		private string _nazwa_samochodu;
		
		private int _id_cena_wynajmu;
		
		private System.Nullable<int> _deleted;
		
		private EntitySet<cena_wynajmu> _cena_wynajmus;
		
		private EntitySet<dane_samochodu> _dane_samochodus;
		
		private EntitySet<wypozyczenia> _wypozyczenias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_samochoduChanging(int value);
    partial void Onid_samochoduChanged();
    partial void Onnazwa_samochoduChanging(string value);
    partial void Onnazwa_samochoduChanged();
    partial void Onid_cena_wynajmuChanging(int value);
    partial void Onid_cena_wynajmuChanged();
    partial void OndeletedChanging(System.Nullable<int> value);
    partial void OndeletedChanged();
    #endregion
		
		public samochodyt()
		{
			this._cena_wynajmus = new EntitySet<cena_wynajmu>(new Action<cena_wynajmu>(this.attach_cena_wynajmus), new Action<cena_wynajmu>(this.detach_cena_wynajmus));
			this._dane_samochodus = new EntitySet<dane_samochodu>(new Action<dane_samochodu>(this.attach_dane_samochodus), new Action<dane_samochodu>(this.detach_dane_samochodus));
			this._wypozyczenias = new EntitySet<wypozyczenia>(new Action<wypozyczenia>(this.attach_wypozyczenias), new Action<wypozyczenia>(this.detach_wypozyczenias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_samochodu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_samochodu
		{
			get
			{
				return this._id_samochodu;
			}
			set
			{
				if ((this._id_samochodu != value))
				{
					this.Onid_samochoduChanging(value);
					this.SendPropertyChanging();
					this._id_samochodu = value;
					this.SendPropertyChanged("id_samochodu");
					this.Onid_samochoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa_samochodu", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nazwa_samochodu
		{
			get
			{
				return this._nazwa_samochodu;
			}
			set
			{
				if ((this._nazwa_samochodu != value))
				{
					this.Onnazwa_samochoduChanging(value);
					this.SendPropertyChanging();
					this._nazwa_samochodu = value;
					this.SendPropertyChanged("nazwa_samochodu");
					this.Onnazwa_samochoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cena_wynajmu", DbType="Int NOT NULL")]
		public int id_cena_wynajmu
		{
			get
			{
				return this._id_cena_wynajmu;
			}
			set
			{
				if ((this._id_cena_wynajmu != value))
				{
					this.Onid_cena_wynajmuChanging(value);
					this.SendPropertyChanging();
					this._id_cena_wynajmu = value;
					this.SendPropertyChanged("id_cena_wynajmu");
					this.Onid_cena_wynajmuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Int")]
		public System.Nullable<int> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="samochodyt_cena_wynajmu", Storage="_cena_wynajmus", ThisKey="id_samochodu", OtherKey="samochody_id_samochodu")]
		public EntitySet<cena_wynajmu> cena_wynajmus
		{
			get
			{
				return this._cena_wynajmus;
			}
			set
			{
				this._cena_wynajmus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="samochodyt_dane_samochodu", Storage="_dane_samochodus", ThisKey="id_samochodu", OtherKey="id_samochodu")]
		public EntitySet<dane_samochodu> dane_samochodus
		{
			get
			{
				return this._dane_samochodus;
			}
			set
			{
				this._dane_samochodus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="samochodyt_wypozyczenia", Storage="_wypozyczenias", ThisKey="id_samochodu", OtherKey="id_samochodu")]
		public EntitySet<wypozyczenia> wypozyczenias
		{
			get
			{
				return this._wypozyczenias;
			}
			set
			{
				this._wypozyczenias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cena_wynajmus(cena_wynajmu entity)
		{
			this.SendPropertyChanging();
			entity.samochodyt = this;
		}
		
		private void detach_cena_wynajmus(cena_wynajmu entity)
		{
			this.SendPropertyChanging();
			entity.samochodyt = null;
		}
		
		private void attach_dane_samochodus(dane_samochodu entity)
		{
			this.SendPropertyChanging();
			entity.samochodyt = this;
		}
		
		private void detach_dane_samochodus(dane_samochodu entity)
		{
			this.SendPropertyChanging();
			entity.samochodyt = null;
		}
		
		private void attach_wypozyczenias(wypozyczenia entity)
		{
			this.SendPropertyChanging();
			entity.samochodyt = this;
		}
		
		private void detach_wypozyczenias(wypozyczenia entity)
		{
			this.SendPropertyChanging();
			entity.samochodyt = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uzytkownicy")]
	public partial class uzytkownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_uzytkownika;
		
		private string _nazwa_uzytkownika;
		
		private string _haslo;
		
		private string _typ;
		
		private EntitySet<klient> _klients;
		
		private EntitySet<pracownik> _pracowniks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_uzytkownikaChanging(int value);
    partial void Onid_uzytkownikaChanged();
    partial void Onnazwa_uzytkownikaChanging(string value);
    partial void Onnazwa_uzytkownikaChanged();
    partial void OnhasloChanging(string value);
    partial void OnhasloChanged();
    partial void OntypChanging(string value);
    partial void OntypChanged();
    #endregion
		
		public uzytkownicy()
		{
			this._klients = new EntitySet<klient>(new Action<klient>(this.attach_klients), new Action<klient>(this.detach_klients));
			this._pracowniks = new EntitySet<pracownik>(new Action<pracownik>(this.attach_pracowniks), new Action<pracownik>(this.detach_pracowniks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_uzytkownika", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_uzytkownika
		{
			get
			{
				return this._id_uzytkownika;
			}
			set
			{
				if ((this._id_uzytkownika != value))
				{
					this.Onid_uzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._id_uzytkownika = value;
					this.SendPropertyChanged("id_uzytkownika");
					this.Onid_uzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa_uzytkownika", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nazwa_uzytkownika
		{
			get
			{
				return this._nazwa_uzytkownika;
			}
			set
			{
				if ((this._nazwa_uzytkownika != value))
				{
					this.Onnazwa_uzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._nazwa_uzytkownika = value;
					this.SendPropertyChanged("nazwa_uzytkownika");
					this.Onnazwa_uzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haslo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string haslo
		{
			get
			{
				return this._haslo;
			}
			set
			{
				if ((this._haslo != value))
				{
					this.OnhasloChanging(value);
					this.SendPropertyChanging();
					this._haslo = value;
					this.SendPropertyChanged("haslo");
					this.OnhasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this.OntypChanging(value);
					this.SendPropertyChanging();
					this._typ = value;
					this.SendPropertyChanged("typ");
					this.OntypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uzytkownicy_klient", Storage="_klients", ThisKey="id_uzytkownika", OtherKey="uzytkownicy_id_uzytkownika")]
		public EntitySet<klient> klients
		{
			get
			{
				return this._klients;
			}
			set
			{
				this._klients.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="uzytkownicy_pracownik", Storage="_pracowniks", ThisKey="id_uzytkownika", OtherKey="uzytkownicy_id_uzytkownika")]
		public EntitySet<pracownik> pracowniks
		{
			get
			{
				return this._pracowniks;
			}
			set
			{
				this._pracowniks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_klients(klient entity)
		{
			this.SendPropertyChanging();
			entity.uzytkownicy = this;
		}
		
		private void detach_klients(klient entity)
		{
			this.SendPropertyChanging();
			entity.uzytkownicy = null;
		}
		
		private void attach_pracowniks(pracownik entity)
		{
			this.SendPropertyChanging();
			entity.uzytkownicy = this;
		}
		
		private void detach_pracowniks(pracownik entity)
		{
			this.SendPropertyChanging();
			entity.uzytkownicy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wypozyczenia")]
	public partial class wypozyczenia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_wypozyczenia;
		
		private int _id_klienta;
		
		private int _id_pracownika;
		
		private int _id_samochodu;
		
		private System.DateTime _data_wypozyczenia;
		
		private System.DateTime _data_oddania;
		
		private byte _stan_wypozyczenia;
		
		private EntityRef<klient> _klient;
		
		private EntityRef<pracownik> _pracownik;
		
		private EntityRef<samochodyt> _samochody;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_wypozyczeniaChanging(int value);
    partial void Onid_wypozyczeniaChanged();
    partial void Onid_klientaChanging(int value);
    partial void Onid_klientaChanged();
    partial void Onid_pracownikaChanging(int value);
    partial void Onid_pracownikaChanged();
    partial void Onid_samochoduChanging(int value);
    partial void Onid_samochoduChanged();
    partial void Ondata_wypozyczeniaChanging(System.DateTime value);
    partial void Ondata_wypozyczeniaChanged();
    partial void Ondata_oddaniaChanging(System.DateTime value);
    partial void Ondata_oddaniaChanged();
    partial void Onstan_wypozyczeniaChanging(byte value);
    partial void Onstan_wypozyczeniaChanged();
    #endregion
		
		public wypozyczenia()
		{
			this._klient = default(EntityRef<klient>);
			this._pracownik = default(EntityRef<pracownik>);
			this._samochody = default(EntityRef<samochodyt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_wypozyczenia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_wypozyczenia
		{
			get
			{
				return this._id_wypozyczenia;
			}
			set
			{
				if ((this._id_wypozyczenia != value))
				{
					this.Onid_wypozyczeniaChanging(value);
					this.SendPropertyChanging();
					this._id_wypozyczenia = value;
					this.SendPropertyChanged("id_wypozyczenia");
					this.Onid_wypozyczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", DbType="Int NOT NULL")]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					if (this._klient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_klientaChanging(value);
					this.SendPropertyChanging();
					this._id_klienta = value;
					this.SendPropertyChanged("id_klienta");
					this.Onid_klientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pracownika", DbType="Int NOT NULL")]
		public int id_pracownika
		{
			get
			{
				return this._id_pracownika;
			}
			set
			{
				if ((this._id_pracownika != value))
				{
					if (this._pracownik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pracownikaChanging(value);
					this.SendPropertyChanging();
					this._id_pracownika = value;
					this.SendPropertyChanged("id_pracownika");
					this.Onid_pracownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_samochodu", DbType="Int NOT NULL")]
		public int id_samochodu
		{
			get
			{
				return this._id_samochodu;
			}
			set
			{
				if ((this._id_samochodu != value))
				{
					if (this._samochody.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_samochoduChanging(value);
					this.SendPropertyChanging();
					this._id_samochodu = value;
					this.SendPropertyChanged("id_samochodu");
					this.Onid_samochoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_wypozyczenia", DbType="Date NOT NULL")]
		public System.DateTime data_wypozyczenia
		{
			get
			{
				return this._data_wypozyczenia;
			}
			set
			{
				if ((this._data_wypozyczenia != value))
				{
					this.Ondata_wypozyczeniaChanging(value);
					this.SendPropertyChanging();
					this._data_wypozyczenia = value;
					this.SendPropertyChanged("data_wypozyczenia");
					this.Ondata_wypozyczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_oddania", DbType="Date NOT NULL")]
		public System.DateTime data_oddania
		{
			get
			{
				return this._data_oddania;
			}
			set
			{
				if ((this._data_oddania != value))
				{
					this.Ondata_oddaniaChanging(value);
					this.SendPropertyChanging();
					this._data_oddania = value;
					this.SendPropertyChanged("data_oddania");
					this.Ondata_oddaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stan_wypozyczenia", DbType="TinyInt NOT NULL")]
		public byte stan_wypozyczenia
		{
			get
			{
				return this._stan_wypozyczenia;
			}
			set
			{
				if ((this._stan_wypozyczenia != value))
				{
					this.Onstan_wypozyczeniaChanging(value);
					this.SendPropertyChanging();
					this._stan_wypozyczenia = value;
					this.SendPropertyChanged("stan_wypozyczenia");
					this.Onstan_wypozyczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="klient_wypozyczenia", Storage="_klient", ThisKey="id_klienta", OtherKey="id_klienta", IsForeignKey=true)]
		public klient klient
		{
			get
			{
				return this._klient.Entity;
			}
			set
			{
				klient previousValue = this._klient.Entity;
				if (((previousValue != value) 
							|| (this._klient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._klient.Entity = null;
						previousValue.wypozyczenias.Remove(this);
					}
					this._klient.Entity = value;
					if ((value != null))
					{
						value.wypozyczenias.Add(this);
						this._id_klienta = value.id_klienta;
					}
					else
					{
						this._id_klienta = default(int);
					}
					this.SendPropertyChanged("klient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pracownik_wypozyczenia", Storage="_pracownik", ThisKey="id_pracownika", OtherKey="id_pracownika", IsForeignKey=true)]
		public pracownik pracownik
		{
			get
			{
				return this._pracownik.Entity;
			}
			set
			{
				pracownik previousValue = this._pracownik.Entity;
				if (((previousValue != value) 
							|| (this._pracownik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pracownik.Entity = null;
						previousValue.wypozyczenias.Remove(this);
					}
					this._pracownik.Entity = value;
					if ((value != null))
					{
						value.wypozyczenias.Add(this);
						this._id_pracownika = value.id_pracownika;
					}
					else
					{
						this._id_pracownika = default(int);
					}
					this.SendPropertyChanged("pracownik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="samochodyt_wypozyczenia", Storage="_samochody", ThisKey="id_samochodu", OtherKey="id_samochodu", IsForeignKey=true)]
		public samochodyt samochodyt
		{
			get
			{
				return this._samochody.Entity;
			}
			set
			{
				samochodyt previousValue = this._samochody.Entity;
				if (((previousValue != value) 
							|| (this._samochody.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._samochody.Entity = null;
						previousValue.wypozyczenias.Remove(this);
					}
					this._samochody.Entity = value;
					if ((value != null))
					{
						value.wypozyczenias.Add(this);
						this._id_samochodu = value.id_samochodu;
					}
					else
					{
						this._id_samochodu = default(int);
					}
					this.SendPropertyChanged("samochodyt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
